config:
    shim:
        'jquery.multiselect':
            deps:
                - 'jquery-ui'
        'jquery.multiselect.filter':
            deps:
                - 'jquery.multiselect'
    map:
        '*':
            'jquery.multiselect': 'orofilter/js/extend/multiselect'
            'jquery.multiselect.filter': 'orofilter/js/extend/multiselect-filter'
        'orofilter/js/extend/multiselect':
            'jquery.multiselect': 'jquery.multiselect'
        'orofilter/js/extend/multiselect-filter':
            'jquery.multiselect.filter': 'jquery.multiselect.filter'
    paths:
        'jquery.multiselect': 'bundles/orofilter/lib/multiselect/jquery.multiselect.js'
        'jquery.multiselect.filter': 'bundles/orofilter/lib/multiselect/jquery.multiselect.filter.js'
        'oro/filter/abstract-filter': 'bundles/orofilter/js/filter/abstract-filter.js'
        'oro/filter/choice-filter': 'bundles/orofilter/js/filter/choice-filter.js'
        'oro/filter/date-filter': 'bundles/orofilter/js/filter/date-filter.js'
        'oro/filter/datetime-filter': 'bundles/orofilter/js/filter/datetime-filter.js'
        'oro/filter/empty-filter': 'bundles/orofilter/js/filter/empty-filter.js'
        'oro/filter/multiselect-filter': 'bundles/orofilter/js/filter/multiselect-filter.js'
        'oro/filter/none-filter': 'bundles/orofilter/js/filter/none-filter.js'
        'oro/filter/number-filter': 'bundles/orofilter/js/filter/number-filter.js'
        'oro/filter/select-filter': 'bundles/orofilter/js/filter/select-filter.js'
        'oro/filter/select-row-filter': 'bundles/orofilter/js/filter/select-row-filter.js'
        'oro/filter/text-filter': 'bundles/orofilter/js/filter/text-filter.js'
        'orofilter/js/formatter/abstract-formatter': 'bundles/orofilter/js/formatter/abstract-formatter.js'
        'orofilter/js/formatter/number-formatter': 'bundles/orofilter/js/formatter/number-formatter.js'
        'orofilter/js/filters-manager': 'bundles/orofilter/js/filters-manager.js'
        'orofilter/js/collection-filters-manager': 'bundles/orofilter/js/collection-filters-manager.js'
        'orofilter/js/datafilter-builder': 'bundles/orofilter/js/datafilter-builder.js'
        'orofilter/js/datafilter-wrapper': 'bundles/orofilter/js/datafilter-wrapper.js'
        'orofilter/js/multiselect-decorator': 'bundles/orofilter/js/multiselect-decorator.js'
