oro_system_configuration:
    groups:
        notifications:
            icon:   icon-bullhorn
            title:  'Notifications'
        email_notifications_settings:
            title:  'General contact'
    fields:
        oro_notification.email_notification_sender_email:
            data_type: string
            type: email
            options:
                label: 'Sender email'
        oro_notification.email_notification_sender_name:
            data_type: string
            type: text
            options:
                label: 'Sender name'
    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            notifications:
                                children:
                                    email_notifications_settings:
                                        children:
                                            - oro_notification.email_notification_sender_email
                                            - oro_notification.email_notification_sender_name

    api_tree:
        notifications:
            oro_notification.email_notification_sender_email: ~
            oro_notification.email_notification_sender_name: ~
