oro_entity_config:
    extend:
        entity:
            require_js:                     ['oroentityextend/js/init-entity-extend-apply', 'oroentityextend/js/init-entity-extend-relation', 'oroentityextend/js/delete-restore-field']
            grid_action:
                -
                    name:                   'Remove'
                    route:                  'oro_entityextend_entity_remove'
                    type:                   'ajaxdelete'
                    icon:                   'trash'
                    filter:                 { owner: 'Custom', state: ['New', 'Requires update', 'Active']}
                    args:                   ['id']
                -
                    name:                   'Restore'
                    route:                  'oro_entityextend_entity_unremove'
                    type:                   'ajax'
                    icon:                   'backward'
                    filter:                 { owner: 'Custom', state: ['Deleted']}
                    args:                   ['id']
            layout_action:
                -
                    name:                   'Create Entity'
                    route:                  'oro_entityextend_entity_create'
            items:
                owner:
                    options:
                        priority:           40
                        auditable:          false
                        default_value:      'System'
                        indexed:            true
                    grid:
                        type:               string
                        label:              'Type'
                        filter_type:        choice
                        choices:            {System: 'System', Custom: 'Custom'}
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        true

                is_extend:
                    options:
                        priority:           27
                        default_value:      false
                        auditable:          false
                        indexed:            true
                    grid:
                        type:               boolean
                        label:              'Is Extend'
                        filter_type:        boolean
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        false

                state:
                    options:
                        priority:           25
                        default_value:      'Active'
                        indexed:            true
                    grid:
                        type:               string
                        label:              'Schema status'
                        filter_type:        choice
                        choices:            {system: '', new: 'New', active: 'Active', updated: 'Requires update', deleted: 'To be deleted'}
                        required:           true
                        sortable:           true
                        filterable:         false
                        show_filter:        false

                is_deleted:
                    options:
                        default_value:      false
                        auditable:          false
                        indexed:            true
                    grid:
                        renderable:         false
                        query:
                            operator:       '!='
                            value:          true

                unique_key:
                    options:
                        auditable:          false

                index:
                    options:
                        auditable:          false

                upgradeable:
                    options:
                        auditable:          false
                        default_value:      true

                relation:
                    options:
                        auditable:          false

                schema:
                    options:
                        auditable:          false

        field:
            grid_action:
                -
                    name:                   'Remove'
                    route:                  'oro_entityextend_field_remove'
                    type:                   'ajax'
                    icon:                   'trash'
                    filter:                 { owner: 'Custom', state: ['New', 'Requires update', 'Active'] }
                    args:                   ['id']
                -
                    name:                   'Restore'
                    route:                  'oro_entityextend_field_unremove'
                    type:                   'ajax'
                    icon:                   'backward'
                    filter:                 { owner: 'Custom', state: ['Deleted'] }
                    args:                   ['id']
            layout_action:
                -
                    name:                   'Manage unique keys'
                    route:                  'oro_entityextend_entity_unique_key'
                    entity_id:              true
                    filter:                 { is_extend: true }
                -
                    name:                   'Create field'
                    route:                  'oro_entityextend_field_create'
                    entity_id:              true
                    filter:                 { is_extend: true }
                -
                    name:                   'Update schema'
                    route:                  'oro_entityextend_update'
                    entity_id:              true
                    aCss:                   'btn-danger entity-extend-apply'
                    void:                   true
                    filter:                 { upgradeable: true, state: ['New', 'Requires update', 'Deleted'] }
            items:
                owner:
                    options:
                        priority:           20
                        default_value:      'System'
                        auditable:          false
                        indexed:            true
                    grid:
                        type:               string
                        label:              'Type'
                        filter_type:        string
                        required:           true
                        sortable:           true
                        filterable:         false
                        show_filter:        false

                state:
                    options:
                        priority:           25
                        default_value:      'Active'
                        indexed:            true
                    grid:
                        type:               string
                        label:              'Schema status'
                        filter_type:        choice
                        choices:            { new: 'New', applied: 'Applied', updated: 'Requires update', deleted: 'To be deleted'}
                        required:           true
                        sortable:           true
                        filterable:         false
                        show_filter:        false

                is_extend:
                    options:
                        default_value:      false
                        auditable:          false

                extend:
                    options:
                        default_value:      false
                        auditable:          false

                length:
                    options:
                        require_schema_update: true
                        default_value:      255
                        allowed_type:       [string]
                        required_property:
                            config_id:
                                scope:      extend
                            code:           owner
                            value:          Custom
                    constraints:
                        - Regex:            "/^[0-9]*$/"
                        - Range:
                            min:            1
                            max:            255
                    form:
                        type:               oro_entity_extend_text
                        options:
                            required:       false
                            label:          'Length'
                            block:          general
                            subblock:       properties

                precision:
                    options:
                        require_schema_update: true
                        default_value:      2
                        allowed_type:       [decimal]
                        required_property:
                            config_id:
                                scope:      extend
                            code:           owner
                            value:          Custom
                    constraints:
                        - Regex:            "/^[0-9]*$/"
                        - Range:
                            min:            0
                    form:
                        type:               oro_entity_extend_text
                        options:
                            required:       false
                            label:          'Precision'
                            block:          general
                            subblock:       properties

                scale:
                    options:
                        require_schema_update: true
                        default_value:      2
                        allowed_type:       [decimal]
                        required_property:
                            config_id:
                                scope:      extend
                            code:           owner
                            value:          Custom
                    constraints:
                        - Regex:            "/^[0-9]*$/"
                        - Range:
                            min:            0
                    form:
                        type:               oro_entity_extend_text
                        options:
                            required:       false
                            label:          'Scale'
                            block:          general
                            subblock:       properties

                is_deleted:
                    options:
                        default_value:      false
                        auditable:          false
                        indexed:            true
                    grid:
                        renderable:         false
                        query:
                            operator:       '!='
                            value:          true

                is_inverse:
                    options:
                        default_value:      false
                        auditable:          false

                #
                # Relations form type fields
                #
                relation:
                    options:
                        allowed_type:       [oneToMany, manyToOne, manyToMany]
                        auditable:          false
                        required_property:
                            config_id:
                                field_name: null
                                scope:      extend
                            code:           is_extend
                            value:          true
                    form:
                        type:               oro_entity_relation_type
                        options:
                            block:          general
                            subblock:       properties

                relation_key: # string
                    options:
                        auditable:          false

                # indicated whether the relation has the default value or not
                # for example regular many-to-many or one-to-many have the default value,
                # but you can create them without the default value
                without_default: # bool
                    options:
                        auditable:          false

                target_entity:
                    options:
                        auditable:          false

                target_field:
                    options:
                        auditable:          false

                target_grid:
                    options:
                        auditable:          false

                target_title:
                    options:
                        auditable:          false

                target_detailed:
                    options:
                        auditable:          false

                #
                # OptionSet form type fields
                #
                set_expanded:
                    options:
                        allowed_type:       [optionSet]
                        create_only:        true
                    form:
                        type:               oro_entity_extend_choice
                        options:
                            required:       false
                            choices:        ['No', 'Yes']
                            empty_value:    false
                            label:          'Expanded'
                            attr:
                                class:      is-option-set-expanded
                            block:          general
                            subblock:       properties

                set_options:
                    options:
                        allowed_type:       [optionSet]
                        auditable:          false
                    form:
                        type:               oro_entity_option_set_collection
                        options:
                            required:       false
                            label:          'Options'
                            block:          general
                            subblock:       properties
                            type:           oro_entity_option_set
                            tooltip:        oro.entity_extend.field.option_set.option.tooltip
