oro_system_configuration:
    fields:
        oro_navigation.maxItems:
            data_type: integer
        oro_navigation.title_suffix:
            data_type: string
        oro_navigation.title_delimiter:
            data_type: string
        oro_navigation.breadcrumb_menu:
            data_type: string

    api_tree:
        look-and-feel:
            oro_navigation.maxItems: ~
            oro_navigation.title_suffix: ~
            oro_navigation.title_delimiter: ~
            oro_navigation.breadcrumb_menu: ~
