oro_system_configuration:
    groups:
        attachment_settings:
            icon:   icon-file
            title:  oro.attachment.config.attachment.label
        attachment_mime_types_settings:
            title:  oro.attachment.config.mime_types.label

    fields:
        oro_attachment.upload_file_mime_types:
            data_type: string
            type: textarea
            options:
                label:   oro.attachment.config.upload_file_mime_types.label
                tooltip: oro.attachment.form.tooltip.file_mime_types
        oro_attachment.upload_image_mime_types:
            data_type: string
            type: textarea
            options:
                label: oro.attachment.config.upload_image_mime_types.label
                tooltip: oro.attachment.form.tooltip.image_mime_types

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            attachment_settings:
                                priority: -10
                                children:
                                    attachment_mime_types_settings:
                                        children:
                                            - oro_attachment.upload_file_mime_types
                                            - oro_attachment.upload_image_mime_types

    api_tree:
        attachments:
            oro_attachment.upload_file_mime_types: ~
            oro_attachment.upload_image_mime_types: ~
