oro_system_configuration:
    groups:
        application_settings:
            icon:        icon-desktop
            title:       'Application Settings'
            page_reload: true

        application_name_settings:
            title: 'Name'

        navbar_settings:
            title: oro.ui.system_configuration.groups.navbar_settings.title

    fields:
        oro_ui.application_name:
            data_type: string
            type: text
            options:
                label: 'Short Name'

        oro_ui.application_url:
            data_type: string
            type: text
            options:
                label: 'Application URL'

        oro_ui.application_title:
            data_type: string
            type: text
            options:
                label: 'Full Name'

        oro_ui.navbar_position:
            data_type: string
            type: choice
            options:
                label: 'Position'
                choices:
                    top: Top
                    left: Left

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            application_settings:
                                priority: 260
                                children:
                                    application_name_settings:
                                        children:
                                            - oro_ui.application_name
                                            - oro_ui.application_title
                                            - oro_ui.application_url

                            look_and_feel:
                                children:
                                    navbar_settings:
                                        children:
                                            - oro_ui.navbar_position

    api_tree:
        application:
            oro_ui.application_name: ~
            oro_ui.application_title: ~
            oro_ui.application_url: ~
        look-and-feel:
            oro_ui.navbar_position: ~
