oro_system_configuration:
    groups:
        localization:
            title: 'Localization'
            icon:  'icon-flag'
            page_reload: true
        language_settings:
            title: 'Language settings'
            icon:  'icon-font'
        language_languages:
            title: 'Languages'
        locale_settings:
            title: 'Localization options'
        map_settings:
            title: 'Map options'

    fields:
        oro_locale.locale:
            data_type: string
            type: oro_locale
            priority: 70
            options:
                label: 'Locale'
                tooltip: oro.locale.form.tooltip.locale
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.country:
            data_type: string
            type: oro_locale_country
            priority: 60
            options:
                label: 'Primary Location'
                tooltip: oro.locale.form.tooltip.location
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.format_address_by_address_country:
            data_type: boolean
            type: oro_config_checkbox
            priority: 50
            options:
                label: 'Format address per country'
                tooltip: oro.locale.form.tooltip.format_address_by_address_country
                required: true

        oro_locale.language:
            data_type: string
            type: oro_language
            priority: 40
            options:
                label: 'Default Language'
                tooltip: oro.locale.form.tooltip.language
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.languages:
            data_type: array
            type: oro_language
            priority: 35
            options:
                label: 'Supported languages'
                tooltip: oro.locale.form.tooltip.languages
                required: true
                multiple: true
                constraints:
                    - NotBlank: ~

        oro_locale.timezone:
            data_type: string
            type: oro_locale_timezone
            priority: 30
            options:
                label: 'Timezone'
                tooltip: oro.locale.form.tooltip.timezone
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.currency:
            data_type: string
            type: oro_currency
            priority: 20
            options:
                label: 'Currency'
                tooltip: oro.locale.form.tooltip.currency
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.quarter_start:
            data_type: array
            type: oro_quarter
            priority: 30
            options:
                label: 'First Quarter Starts on'
                tooltip: oro.locale.form.tooltip.quarter_start
                required: true
                constraints:
                    - NotBlank: ~

        oro_locale.temperature_unit:
            data_type: string
            type: choice
            priority: 20
            options:
                label: 'Temperature Unit'
                tooltip: oro.locale.form.tooltip.temperature_unit
                required: true
                constraints:
                    - NotBlank: ~
                choices:
                    fahrenheit: 'Fahrenheit'
                    celsius: 'Celsius'

        oro_locale.wind_speed_unit:
            data_type: string
            type: choice
            priority: 10
            options:
                label: 'Wind Speed Unit'
                tooltip: oro.locale.form.tooltip.wind_speed_unit
                required: true
                constraints:
                    - NotBlank: ~
                choices:
                    miles_per_hour: 'Miles per hour'
                    kilometers_per_hour: 'Kilometers per hour'
                    meters_per_second: 'Meters per second'

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            localization:
                                priority: 255
                                children:
                                    locale_settings:
                                        priority: 100
                                        children:
                                            - oro_locale.locale
                                            - oro_locale.country
                                            - oro_locale.format_address_by_address_country
                                            - oro_locale.timezone
                                            - oro_locale.currency
                                            - oro_locale.quarter_start
                                    map_settings:
                                        priority: 50
                                        children:
                                            - oro_locale.temperature_unit
                                            - oro_locale.wind_speed_unit
                            language_settings:
                                priority: 230
                                children:
                                    language_languages:
                                        children:
                                            - oro_locale.language
                                            - oro_locale.languages

    api_tree:
        localization:
            oro_locale.language: ~
            oro_locale.languages: ~
            oro_locale.locale: ~
            oro_locale.country: ~
            oro_locale.format_address_by_address_country: ~
            oro_locale.timezone: ~
            oro_locale.currency: ~
            oro_locale.quarter_start: ~
            oro_locale.temperature_unit: ~
            oro_locale.wind_speed_unit: ~

