config:
    shim:
        'backgrid':
            deps:
                - 'jquery'
                - 'underscore'
                - 'backbone'
            exports: 'Backgrid'
        'backgrid/moment':
            deps:
                - 'jquery'
                - 'underscore'
                - 'backbone'
                - 'backgrid'
                - 'moment'
        'moment':
            exports:
                - 'moment'
    paths:
        'backbone-pageable-collection': 'bundles/orodatagrid/lib/backbone-pageable.js'
        'backgrid': 'bundles/orodatagrid/lib/backgrid/backgrid.js'

        'orodatagrid/js/datagrid/action-launcher': 'bundles/orodatagrid/js/datagrid/action-launcher.js'
        'oro/datagrid/action/abstract-action': 'bundles/orodatagrid/js/datagrid/action/abstract-action.js'
        'oro/datagrid/action/delete-action': 'bundles/orodatagrid/js/datagrid/action/delete-action.js'
        'oro/datagrid/action/ajax-action': 'bundles/orodatagrid/js/datagrid/action/ajax-action.js'
        'oro/datagrid/action/ajaxdelete-action': 'bundles/orodatagrid/js/datagrid/action/ajaxdelete-action.js'
        'oro/datagrid/action/mass-action': 'bundles/orodatagrid/js/datagrid/action/mass-action.js'
        'oro/datagrid/action/delete-mass-action': 'bundles/orodatagrid/js/datagrid/action/delete-mass-action.js'
        'oro/datagrid/action/model-action': 'bundles/orodatagrid/js/datagrid/action/model-action.js'
        'oro/datagrid/action/navigate-action': 'bundles/orodatagrid/js/datagrid/action/navigate-action.js'
        'oro/datagrid/action/refresh-collection-action': 'bundles/orodatagrid/js/datagrid/action/refresh-collection-action.js'
        'oro/datagrid/action/reset-collection-action': 'bundles/orodatagrid/js/datagrid/action/reset-collection-action.js'
        'oro/datagrid/action/export-action': 'bundles/orodatagrid/js/datagrid/action/export-action.js'
        'orodatagrid/js/datagrid/actions-panel': 'bundles/orodatagrid/js/datagrid/actions-panel.js'
        'orodatagrid/js/datagrid/column/action-column': 'bundles/orodatagrid/js/datagrid/column/action-column.js'
        'orodatagrid/js/datagrid/body': 'bundles/orodatagrid/js/datagrid/body.js'
        'oro/datagrid/cell/action-cell': 'bundles/orodatagrid/js/datagrid/cell/action-cell.js'
        'oro/datagrid/cell/boolean-cell': 'bundles/orodatagrid/js/datagrid/cell/boolean-cell.js'
        'oro/datagrid/cell/html-cell': 'bundles/orodatagrid/js/datagrid/cell/html-cell.js'
        'oro/datagrid/cell/date-cell': 'bundles/orodatagrid/js/datagrid/cell/date-cell.js'
        'oro/datagrid/cell/datetime-cell': 'bundles/orodatagrid/js/datagrid/cell/datetime-cell.js'
        'oro/datagrid/cell/number-cell': 'bundles/orodatagrid/js/datagrid/cell/number-cell.js'
        'oro/datagrid/cell/select-cell': 'bundles/orodatagrid/js/datagrid/cell/select-cell.js'
        'oro/datagrid/cell/select-row-cell': 'bundles/orodatagrid/js/datagrid/cell/select-row-cell.js'
        'oro/datagrid/cell/string-cell': 'bundles/orodatagrid/js/datagrid/cell/string-cell.js'
        'orodatagrid/js/datagrid/formatter/cell-formatter': 'bundles/orodatagrid/js/datagrid/formatter/cell-formatter.js'
        'orodatagrid/js/datagrid/formatter/datetime-formatter': 'bundles/orodatagrid/js/datagrid/formatter/datetime-formatter.js'
        'orodatagrid/js/datagrid/formatter/number-formatter': 'bundles/orodatagrid/js/datagrid/formatter/number-formatter.js'
        'orodatagrid/js/datagrid/grid': 'bundles/orodatagrid/js/datagrid/grid.js'
        'orodatagrid/js/datagrid/header-cell/header-cell': 'bundles/orodatagrid/js/datagrid/header-cell/header-cell.js'
        'orodatagrid/js/datagrid/header-cell/select-all-header-cell': 'bundles/orodatagrid/js/datagrid/header-cell/select-all-header-cell.js'
        'orodatagrid/js/datagrid/header': 'bundles/orodatagrid/js/datagrid/header.js'

        'orodatagrid/js/totals-builder': 'bundles/orodatagrid/js/totals-builder.js'
        'orodatagrid/js/datagrid/footer': 'bundles/orodatagrid/js/datagrid/footer.js'
        'orodatagrid/js/datagrid/footer/footer-row': 'bundles/orodatagrid/js/datagrid/footer/footer-row.js'
        'orodatagrid/js/datagrid/footer/footer-cell': 'bundles/orodatagrid/js/datagrid/footer/footer-cell.js'

        'orodatagrid/js/datagrid/listener/abstract-listener': 'bundles/orodatagrid/js/datagrid/listener/abstract-listener.js'
        'orodatagrid/js/datagrid/listener/column-form-listener': 'bundles/orodatagrid/js/datagrid/listener/column-form-listener.js'
        'orodatagrid/js/datagrid/listener/callback-listener': 'bundles/orodatagrid/js/datagrid/listener/callback-listener.js'
        'orodatagrid/js/datagrid/page-size': 'bundles/orodatagrid/js/datagrid/page-size.js'
        'orodatagrid/js/datagrid/grid-views/view': 'bundles/orodatagrid/js/datagrid/grid-views/view.js'
        'orodatagrid/js/datagrid/grid-views/model': 'bundles/orodatagrid/js/datagrid/grid-views/model.js'
        'orodatagrid/js/datagrid/grid-views/collection': 'bundles/orodatagrid/js/datagrid/grid-views/collection.js'
        'orodatagrid/js/datagrid/pagination-input': 'bundles/orodatagrid/js/datagrid/pagination-input.js'
        'orodatagrid/js/datagrid/pagination': 'bundles/orodatagrid/js/datagrid/pagination.js'
        'orodatagrid/js/datagrid/row': 'bundles/orodatagrid/js/datagrid/row.js'
        'orodatagrid/js/datagrid/toolbar': 'bundles/orodatagrid/js/datagrid/toolbar.js'
        'orodatagrid/js/datagrid-builder': 'bundles/orodatagrid/js/datagrid-builder.js'
        'orodatagrid/js/pageable-collection': 'bundles/orodatagrid/js/pageable-collection.js'

build:
    paths:
#       Backbone after v.1.1.1 started to support AMD. And that broke a js-build with
#       files which does not support AMD. Backgrid is one of them, therefore it's excluded
        'backgrid': 'empty:'
