oro_system_configuration:
    groups:
        look_and_feel:
            title:       'Display settings'
            icon:        'icon-eye-open'
            page_reload: true

        grid_settings:
            title: 'Data Grid settings'

    fields:
        oro_data_grid.default_per_page:
            data_type: integer
            type: choice
            options:
                label:    'Items per Page by Default'
                choices:
                    10:     10
                    25:     25
                    50:     50
                    100:    100
                constraints:
                    - NotBlank: ~

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            look_and_feel:
                                priority: 210
                                children:
                                    grid_settings:
                                        children:
                                            - oro_data_grid.default_per_page

    api_tree:
        look-and-feel:
            oro_data_grid.default_per_page: ~
