datagrid:
    website-grid:
        source:
            type: orm
            acl_resource: oro_tracking_website_view
            query:
                select:
                    - website.id
                    - website.name
                    - website.identifier
                    - website.url
                    - owner.id as ownerId
                    - CONCAT(owner.firstName, CONCAT(' ', owner.lastName)) as ownerName
                    - website.createdAt
                    - website.updatedAt
                from:
                    - { table: %oro_tracking.tracking_website.class%, alias: website }
                join:
                    left:
                        - { join: website.owner, alias: owner }
        columns:
            name:
                label:         oro.tracking.trackingwebsite.name.label
            identifier:
                label:         oro.tracking.trackingwebsite.identifier.label
            url:
                type:          twig
                label:         oro.tracking.trackingwebsite.url.label
                frontend_type: html
                template:      OroTrackingBundle:TrackingWebsite:Property/url.html.twig
            ownerName:
                type:          twig
                label:         oro.tracking.trackingwebsite.owner.label
                frontend_type: html
                template:      OroTrackingBundle:TrackingWebsite:Property/owner.html.twig
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
        sorters:
            columns:
                name:
                    data_name: website.name
                identifier:
                    data_name: website.identifier
                url:
                    data_name: website.url
                ownerName:
                    data_name: website.ownerName
                createdAt:
                    data_name: website.createdAt
                updatedAt:
                    data_name: website.updatedAt
            default:
                identifier: ASC
        filters:
            columns:
                name:
                    type:      string
                    data_name: website.name
                identifier:
                    type:      string
                    data_name: website.identifier
                url:
                    type:      string
                    data_name: website.url
                ownerName:
                    type:      string
                    data_name: ownerName
                createdAt:
                    type:      datetime
                    data_name: website.createdAt
                updatedAt:
                    type:      datetime
                    data_name: website.updatedAt
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_tracking_website_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_tracking_website_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_tracking_website
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_tracking_website_view
                label:         View
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  oro_tracking_website_update
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  oro_tracking_website_delete
                label:         Delete
                icon:          trash
                link:          delete_link

    tracking-events-grid:
        source:
            type: orm
            acl_resource: oro_tracking_website_view
            query:
                select:
                    - e.id
                    - e.name
                    - e.value
                    - e.userIdentifier
                    - e.url
                    - e.title
                    - e.code
                    - e.loggedAt
                from:
                    - { table: %oro_tracking.tracking_event.class%, alias: e }
        columns:
            name:
                label: oro.tracking.trackingevent.name.label
            value:
                label: oro.tracking.trackingevent.value.label
            userIdentifier:
                label: oro.tracking.trackingevent.userIdentifier.label
            url:
                type: twig
                label: oro.tracking.trackingevent.url.label
                frontend_type: html
                template: OroTrackingBundle:TrackingEvent:Property/url.html.twig
            code:
                label: oro.tracking.trackingevent.code.label
            loggedAt:
                label: oro.tracking.trackingevent.logged_at.label
                frontend_type: datetime
        sorters:
            columns:
                name:
                    data_name: e.name
                value:
                    data_name: e.value
                userIdentifier:
                    data_name: e.userIdentifier
                code:
                    data_name: e.code
                loggedAt:
                    data_name: e.loggedAt
            default:
                loggedAt: DESC
        filters:
            columns:
                name:
                    type:      string
                    data_name: e.name
                value:
                    type:      string
                    data_name: e.value
                userIdentifier:
                    type:      string
                    data_name: e.userIdentifier
                code:
                    type:      string
                    data_name: e.code
                loggedAt:
                    type:      datetime
                    data_name: e.loggedAt
        properties:
            id: ~

    website-tracking-events-grid:
        extends: tracking-events-grid
        source:
            query:
                join:
                    inner:
                        - { join: e.website, alias: w }
                where:
                    and:
                        - w.identifier = :websiteIdentifier
