datagrid:
    base-email-grid:
        source:
            acl_resource: oro_email_view
            type: orm
            query:
                select:
                    - partial e.{id, subject, sentAt}
                from:
                    - { table: OroEmailBundle:Email, alias: e }

        columns:
            fromEmailExpression:
                type: twig
                label: oro.email.from_name.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/from.html.twig
            recipients:
                type: twig
                label: oro.email.recipients.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/recipients.html.twig
            subject:
                type: twig
                label: oro.email.subject.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/subject.html.twig
            sentAt:
                label: oro.email.sent_at.label
                frontend_type: datetime
        properties:
            id: ~
        sorters:
            columns:
                subject: { data_name: e.subject }
                sentAt:  { data_name: e.sentAt }
                fromEmailExpression: { data_name: fromEmailExpression }
            default: { sentAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC }
        options:
            entityHint: email

    simplified-email-grid:
        extends: base-email-grid
        options:
            toolbarOptions:
                turnOffToolbarRecordsNumber: 5
                addResetAction: false

    email-grid:
        extends: base-email-grid
        filters:
            columns:
                fromEmailExpression: { type: string,   data_name: fromEmailExpression }
                subject:             { type: string,   data_name: e.subject }
                sentAt:              { type: datetime, data_name: e.sentAt }

    activity-email-grid:
        extends: email-grid

    user-email-grid:
        extends: email-grid

    dashboard-recent-emails-grid:
        source:
            type: orm
            query:
                select:
                    - partial e.{id, subject, receivedAt, sentAt}
                from:
                    - { table: OroEmailBundle:Email, alias: e }
                join:
                    inner:
                        - { join: e.folders, alias: f }
                        - { join: f.origin, alias: o }
                        - { join: e.fromEmailAddress, alias: a }
                where:
                    and:
                        - o.id IN (:origin_ids)
        properties:
            id: ~
        options:
            entityHint: email
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10

    dashboard-recent-emails-inbox-grid:
        extends: dashboard-recent-emails-grid
        source:
            query:
                where:
                    and:
                        - f.type = '%oro_email.email_folder.entity.class%::INBOX'
        columns:
            receivedAt:
                label: oro.email.received_at.label
                frontend_type: datetime
            fromEmailExpression:
                type: twig
                label: oro.email.from_name.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/from.html.twig
            subject:
                type: twig
                label: oro.email.subject.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/subject.html.twig
        sorters:
            columns:
                fromEmailExpression: { data_name: fromEmailExpression }
                receivedAt:  { data_name: e.receivedAt }
            default:
                receivedAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

    dashboard-recent-emails-sent-grid:
        extends: dashboard-recent-emails-grid
        source:
            query:
                where:
                    and:
                        - f.type = '%oro_email.email_folder.entity.class%::SENT'
        columns:
            sentAt:
                label: oro.email.sent_at.label
                frontend_type: datetime
            recipients:
                type: twig
                label: oro.email.recipients.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/recipients.html.twig
            subject:
                type: twig
                label: oro.email.subject.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/subject.html.twig
        sorters:
            columns:
                sentAt:  { data_name: e.sentAt }
            default:
                sentAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

    email-templates:
        source:
            type: orm
            acl_resource: oro_email_emailtemplate_index
            query:
                select:
                    - t.id
                    - t.entityName
                    - t.name
                    - t.type
                    - t.isSystem
                from:
                    - { table: %oro_email.emailtemplate.entity.class%, alias: t }

        columns:
            entityName:
                label:          oro.email.emailtemplate.entity_name.label
                type:           twig
                template:       OroEntityBundle:Datagrid:Property/entity.html.twig
                frontend_type:  html
                context:
                    entity_provider: @oro_entity.entity_provider
            name:
                label:          oro.email.emailtemplate.name.label
            type:
                frontend_type:  select
                label:          oro.email.emailtemplate.type.label
                choices:        @oro_email.emailtemplate.datagrid_helper->getTypeChoices
            isSystem:
                frontend_type:  boolean
                label:          oro.email.emailtemplate.is_system.label
        properties:
            id: ~
            update_link:
                type: url
                route: oro_email_emailtemplate_update
                params: [ id ]
            clone_link:
                type: url
                route: oro_email_emailtemplate_clone
                params: [ id ]
            delete_link:
                type: url
                route: oro_api_delete_emailtemplate
                params: [ id ]

        filters:
            columns:
                entityName:
                    type:      choice
                    data_name: t.entityName
                    null_value: _empty_
                    options:
                        is_translated_choices: true
                        field_options:
                            multiple:       true
                            choices:        @oro_email.emailtemplate.datagrid_helper->getEntityNames
                name:
                    type:      string
                    data_name: t.name
                type:
                    type:            choice
                    data_name:       t.type
                    options:
                        field_options:
                            choices: @oro_email.emailtemplate.datagrid_helper->getTypeChoices

                isSystem:
                    type:           boolean
                    data_name:      t.isSystem

        sorters:
            columns:
                name:     { data_name: t.name }
                type:     { data_name: t.type }
                isSystem: { data_name: t.isSystem }

        actions:
            update:
                type:         navigate
                label:        oro.email.datagrid.emailtemplate.action.update
                link:         update_link
                icon:         edit
                acl_resource: oro_email_emailtemplate_update
                rowAction:    true
            clone:
                type:         navigate
                label:        oro.email.datagrid.emailtemplate.action.clone
                link:         clone_link
                icon:         copy
                acl_resource: oro_email_emailtemplate_create
            delete:
                type:         delete
                label:        oro.email.datagrid.emailtemplate.action.delete
                acl_resource: oro_email_emailtemplate_delete
                icon:         trash
                link:         delete_link

        action_configuration: @oro_email.emailtemplate.datagrid_helper->getActionConfigurationClosure
        views_list : @oro_email.emailtemplate.datagrid_view_list
        options: { entityHint: email template }
