datagrid:
    # Entity config entities grid
    entityconfig-grid:
        options:
            entityHint: entity
            toolbarOptions:
                pageSize:
                    default_per_page: 100
        source:
            acl_resource: oro_entityconfig_manage
            type: orm
            query:
                select:
                    - ce.id
                    - ce.updated
                    - ce.mode
                from:
                    - { table: OroEntityConfigBundle:EntityConfigModel, alias: ce }
                where:
                    and:
                        - ce.mode <> 'Oro\Bundle\EntityConfigBundle\Config\ConfigModelManager::MODE_HIDDEN'
        columns:
            updated:
                label: oro.ui.updated_at
                frontend_type: datetime

        properties:
            id: ~
            update_link:
                type: url
                route: oro_entityconfig_update
                params:
                    - id
            view_link:
                type: url
                route: oro_entityconfig_view
                params:
                    - id
        actions:
            # @TODO check why those actions dont have ACL
            view:
                type: navigate
                label: View
                icon: eye-open
                link: view_link
                rowAction: true
            update:
                type: navigate
                label: Update
                icon: edit
                link: update_link
        sorters:
            columns:
                updated:
                    data_name: ce.updated
            default:
                entity: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                updated:
                    type: datetime
                    data_name: ce.updated

    # Entity field datagrid
    entityfields-grid:
        options:
            entityHint: fields
            toolbarOptions:
                pageSize:
                    default_per_page: 50
        source:
            # TODO: check oro_entityconfig_view acl (403) right now
            acl_resource: oro_entityconfig_manage
            type: orm
            query:
                select:
                    - cf.id
                    - ce.className
                    - cf.fieldName
                    - cf.type
                    - cf.mode
                from:
                    - { table: OroEntityConfigBundle:FieldConfigModel, alias: cf }

        columns:
            fieldName:
                label: oro.entity_config.field_config.field_name.label
                frontend_type: string
            type:
                label: oro.entity_config.field_config.type.label
                frontend_type: string

        properties:
            update_link:
                type: url
                route: oro_entityconfig_field_update
                params:
                    - id
        actions:
            # @TODO check why those actions dont have ACL
            update:
                type: navigate
                label: Edit
                icon: edit
                link: update_link
                rowAction: true
        sorters:
            columns:
                fieldName:
                    data_name: cf.fieldName
                type:
                    data_name: cf.type
        filters: ~

    # Audit entity log grid
    entity-audit-grid:
        options:
            entityHint: history
        source:
            acl_resource: oro_entityconfig_manage
            type: orm
            query:
                select:
                    - log
                    - >
                      CONCAT(
                        CONCAT(
                            CONCAT(u.firstName, ' '),
                            CONCAT(u.lastName, ' ')
                        ),
                        CONCAT(' - ', u.email)
                      ) as author
                from:
                    - { table: OroEntityConfigBundle:ConfigLog, alias: log }
                join:
                    left:
                        user:
                            join: log.user
                            alias: u
                    inner:
                        diffs:
                            join: log.diffs
                            alias: diff
                            conditionType: WITH

        columns:
            author:
                label: oro.entity_config.config_log.user.label
                type: field
                frontend_type: string
            diffs:
                label: oro.entity_config.config_log.diffs.label
                type: twig
                template: OroEntityConfigBundle:Audit:data.html.twig
                frontend_type: html
                context:
                    config_manager: @oro_entity_config.config_manager
            loggedAt:
                label: oro.entity_config.config_log.logged_at.label
                type: field
                frontend_type: datetime

        sorters:
            columns:
                author:
                    data_name: author
                loggedAt:
                    data_name: log.loggedAt
            default:
                loggedAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

    audit-log-grid:
        extends: entity-audit-grid
        source:
            query:
                join:
                    inner:
                        diffs:
                            condition: diff.className = :objectClass AND diff.fieldName IS NULL
        columns:
            diffs:
                context:
                    is_entity: true

    auditfield-log-grid:
        extends: entity-audit-grid
        source:
            query:
                join:
                    inner:
                        diffs:
                            condition: diff.className = :objectClass AND diff.fieldName = :fieldName
        columns:
            diffs:
                context:
                    is_entity: false
                    field_name: ~ # set from buildBefore in event listener
