Oro\Bundle\ReportBundle\Entity\Report:
    constraints:
        - Oro\Bundle\QueryDesignerBundle\Validator\Constraints\QueryConstraint: ~
    properties:
        name:
            - NotBlank:     ~
            - Length:
                max: 255
        type:
            - NotBlank:     ~
            - Length:
                max: 32
        entity:
            - NotBlank:     ~
            - Length:
                max: 255
