config:
    paths:
        'orosegment/js/app/components/refresh-button': 'bundles/orosegment/js/app/components/refresh-button.js'
        'orosegment/js/app/components/segment-editor': 'bundles/orosegment/js/app/components/segment-editor.js'
